const projects = [
    {
        name: "stylish",
        stack: ['Javascript','HTML5', 'CSS3'],
        type: 'Web',
        visibleKeywords:['frontend'],
        githubUrl: 'https://github.com/AnnaFinnerty/stylish',
        url: 'https://annafinnerty.github.io/stylish/',
        src: ['./img/Stylish1.png'],
        description: 'Interactive logo prototype for hair salon',
        caseStudy: [],
        live: true,
        start: true,
        left: true,
        dark: false,
        logoColor: 'black',
        titleColor: 'white',
        arrowColor: 'dimgray',
        dotColor: 'dimgray',
        bannerColor: 'black',
        buttonColor: 'black',
        collaborators: []
    },
    {
        name: "habit",
        stack: ['Express.js','Mongoose', 'MongoDB','Heroku'],
        type: 'App',
        visibleKeywords:['frontend','backend'],
        url: 'https://gahabit-app.herokuapp.com/',
        githubUrl: 'https://github.com/walter74ucla/Project-2',
        src: ['./img/Habit1.png'],
        description: 'Habit tracker app with RESTful routes',
        caseStudy: [],
        live: true,
        start: false,
        logoColor: 'orange',
        titleColor: 'darkorange',
        arrowColor: 'orange',
        dotColor: 'orange',
        bannerColor: 'black',
        buttonColor: 'darkorange',
        collaborators: [{
            name: 'Walter Sylvester',
            url: 'https://github.com/walter74ucla'
        }]
    },
    {
        name: "still breaking",
        stack: ['React.js','Python', 'Flask', 'SQL', 'API','React-Semantic-UI','Heroku'],
        type: 'App',
        visibleKeywords:['frontend','backend'],
        url: 'https://still-breaking-react.herokuapp.com/',
        githubUrl: 'https://github.com/tbone9/still-breaking-react',
        src: ['./img/StillBreaking1.png'],
        description: 'News content discovery app with multiple APIs',
        caseStudy: [],
        live: true,
        start: false,
        logoColor: 'dodgerblue',
        titleColor: 'navy',
        arrowColor: 'navy',
        dotColor: 'navy',
        bannerColor: 'black',
        buttonColor: 'navy',
        collaborators: [{
            name: 'Tyler Walker',
            url: 'https://github.com/tbone9'
        }]
    },
    {
        name: "citadels",
        stack: ['React.js', 'CSS3', 'AI'],
        type: 'Game',
        visibleKeywords:['frontend','backend'],
        url: 'https://annafinnerty.github.io/Citadels/',
        githubUrl: 'https://github.com/AnnaFinnerty/Citadels',
        src: ['./img/Citadels1.png'],
        description: 'React game with AI opponent',
        caseStudy: [],
        live: true,
        start: true,
        logoColor: 'lightskyblue',
        titleColor: 'coral',
        arrowColor: 'coral',
        dotColor: 'dodgerblue',
        bannerColor: 'black',
        buttonColor: 'dodgerblue',
        collaborators: []
    },
    {
        name: "Word Wrap",
        stack: ['Javascript','HTML5', 'CSS'],
        type: 'Game',
        visibleKeywords:['frontend','backend'],
        url: 'https://annafinnerty.github.io/Citadels/',
        githubUrl: '',
        src: '',
        description: 'Animated JS game using prototype pattern',
        caseStudy: [],
        live: false,
        start: true,
        logoColor: 'white',
        titleColor: 'white',
        arrowColor: 'black',
        dotColor: 'black',
        bannerColor: 'black',
        buttonColor: 'black',
        collaborators: []
    },
    {
        name: "color wheel",
        stack: ['HTMLCanvas', 'HTML5', 'CSS3'],
        type: 'Game',
        visibleKeywords:['frontend','backend'],
        url: 'https://annafinnerty.github.io/named_colorwheel/',
        githubUrl: 'https://github.com/AnnaFinnerty/named_colorwheel',
        src: ['./img/ColorWheel1.png'],
        description: 'React game with AI opponent',
        caseStudy: [],
        live: true,
        start: true,
        logoColor: 'magenta',
        titleColor: 'greenyellow',
        arrowColor: 'magenta',
        dotColor: 'greenyellow',
        bannerColor: 'black',
        buttonColor: 'magenta',
        collaborators: [{
            name: 'Michael Finnerty',
            url: 'https://github.com/MichaelJamesFinnerty'
        }]
    },    
    {
        name: "library",
        stack: ['Express.js','JSX', 'Mongoose', 'MongoDB'],
        type: 'App',
        visibleKeywords:['frontend','backend'],
        url: '',
        githubUrl: '',
        src: ['./img/Habit1.png'],
        description: 'books read/to read app in Express.js',
        caseStudy: [],
        live: false,
        start: true,
        logoColor: 'white',
        titleColor: 'white',
        arrowColor: 'black',
        dotColor: 'white',
        bannerColor: 'black',
        buttonColor: 'black',
        collaborators: []
    },
    {
        name: "maura",
        stack: ['Java','jdbc', 'Jackson'],
        type: 'Java Program',
        visibleKeywords:['backend'],
        url: '',
        githubUrl: '',
        src: [''],
        description: 'Interface to algorhytymic match generator between missing persons and unidentified remains',
        caseStudy: [],
        live: false,
        start: false,
        logoColor: 'white',
        titleColor: 'white',
        arrowColor: 'black',
        dotColor: 'white',
        bannerColor: 'black',
        buttonColor: 'black',
        collaborators: []
    }
]

export default projects